data_type : 'Celeb'

latent_dim : 100
im_size : 64
im_channels : 3

generator_channels : [1024, 512, 256, 128]
generator_kernel_size: [4, 4, 4, 4, 4]
generator_stride: [2, 2, 2, 2, 2]
generator_padding: [0, 1, 1, 1, 1]
generator_output_padding: [0, 0, 0, 0, 0]

discriminator_channels : [128, 256, 512, 1024]
discriminator_kernel_size: [4, 4, 4, 4, 4]
discriminator_stride: [2, 2, 2, 2, 2]
discriminator_padding: [1, 1, 1, 1, 0]

batch_size : 64
epochs : 5
lr : 0.0005
num_workers : 4
betas1 : 0.5
betas2 : 0.999

mod_label: 1
recon_loss_target: 0.016
